### ISSUE TITLE
Small issue with Mk2Expansion and NFElectrical

### ISSUE THREAD

**Issue by ruifung** [ABZB/Mk2_Extended_KSPI_Integration#1]
It's just a minor issue as Mk2Expansion does not include :FOR[Mk2Expansion] statements on it's modulemanager patches, therefore resulting in the game getting stuck on your patches.

I believe the NFE patch from the mk2 mod is being applied before yours.

Probably not really an issue on your side, but as I'm lazy to make a forum account to post, I'll just leave this issue to notify you.

**Comment by ABZB** [comment]
it should not be an issue - MM accepts references to the top-level directory within GameData - so if I had :BEFORE[Foo], that would run before anything in GameData/Foo/

**Comment by ABZB** [comment]
His NFE patch has a NEEDS[!KSPIntegration], but I was asked on my end to make both that NFE reactor and my KSPI reactors work when both KPSI & NFE are installed. basically, if NFE is not installed, I make my KSPI reactors, then remove the original part. If both NFE is present, I leave the original part untouched, and it gets the NFE module from MK2-E's own patch.

However, if you are seeing a reactor-part that has both KSPI & NFE reactor modules at once, then there is a problem somewhere.

**Comment by ruifung** [comment]
Except that when it gets stuck (on that mk2 CP gen), adding a :FOR to it on my side seems to have fixed it.

I just pretty much added a :FOR[Mk2Expansion]
In Mk2X_NFE_Functionality.cfg and it fixed my issue - otherwise it gets stuck compiling said part.

I'm not even sure what I'm getting, I got stuck on loading screen after all.

**Comment by ABZB** [comment]
FOR what? and what did you add it to? do you have NFE installed? Confirm
you have the current version?

**Comment by ruifung** [comment]
For what? the mk2expansions NFE patch.. it's not really a issue with the configs on this side.

And yes, I have the current versions. (CKAN seems to have not picked up the latest version of this =.=)

**Comment by ABZB** [comment]
ah - good thing you said that, I uploaded the wrong directory. it is now fixed.
